version: '3.8'

services:
  frontend:
    image: vonodev/my-fe:latest
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    image: vonodev/my-be:latest
    ports:
      - "3000:3000"
    env_file:
      - .env
