name: Debug CI/CD Deployment

on:
  push:
    branches: [ master ]

jobs:
  debug-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Debug - Show environment
      run: |
        echo "Runner OS: $RUNNER_OS"
        echo "GitHub Actor: $GITHUB_ACTOR"
        echo "GitHub Repository: $GITHUB_REPOSITORY"
        echo "Current Directory: $(pwd)"

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      run: |
        echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
        echo "Docker login successful"

    - name: Build and push Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/my-app:latest .
        docker push ${{ secrets.DOCKER_USERNAME }}/my-app:latest
        echo "Image built and pushed"

    - name: Debug - Verify Docker images
      run: |
        docker images
        echo "Listing Docker images complete"

    - name: Deploy to EC2 (Debug Mode)
      env:
        SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
        HOST: ${{ secrets.EC2_HOST }}
      run: |
        echo "SSH Key and Host set"
        ssh -o StrictHostKeyChecking=no -i <(echo "$SSH_KEY") ec2-user@$HOST << 'EOF'
          echo "Connected to EC2"
          docker --version
          docker ps -a
          echo "Docker commands executed"
        EOF

    - name: Final Debug Output
      run: |
        echo "Workflow completed. Check logs for details."