name: CI/CD with DockerHub

on:
  push:
    branches: [ master ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v3
      
    - name: Log in to Docker Hub
      run: |
        echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
        echo "Docker login successful"

    - name: Build and push FE image
      run: |
        cd client
        echo "VITE_BACKEND_DOMAIN=/api" > .env
        npm install
        npm run build
        docker build -t ${{ secrets.DOCKER_USERNAME }}/my-fe:latest .
        docker push ${{ secrets.DOCKER_USERNAME }}/my-fe:latest


    - name: Build and push BE image
      run: |
        cd server
        echo "MONGO_URI=${{ secrets.MONGO_URI }}" >> .env
        echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> .env
        docker build -t ${{ secrets.DOCKER_USERNAME }}/my-be:latest .
        docker push ${{ secrets.DOCKER_USERNAME }}/my-be:latest
        echo "BE image built and pushed"

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

    - name: Deploy on EC2 via SSH
      env:
        HOST: ${{ secrets.EC2_HOST }}
      run: |
        echo "SSH connection attempt to $HOST"
        ssh -o StrictHostKeyChecking=no ubuntu@$HOST << 'EOF'
          echo "Connected to EC2 at $(date)"
          docker --version
          docker pull ${{ secrets.DOCKER_USERNAME }}/my-fe:latest
          docker pull ${{ secrets.DOCKER_USERNAME }}/my-be:latest
          cd ~/app || echo "Directory ~/app not found, skipping"
          docker-compose down || echo "docker-compose down failed, skipping"
          docker-compose up -d || echo "docker-compose up failed, skipping"
          echo "Deployment commands executed"
        EOF

    - name: Final Debug Output
      run: |
        echo "Workflow completed. Check logs for details."
