name: CI/CD with DockerHub

on:
  push:
    branches: [master]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

    - name: Build and push FE image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/my-fe:latest ./client
        docker push ${{ secrets.DOCKER_USERNAME }}/my-fe:latest

    - name: Build and push BE image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/my-be:latest ./server
        docker push ${{ secrets.DOCKER_USERNAME }}/my-be:latest

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

    - name: Deploy on EC2 via SSH
      run: |
        ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_HOST }} << 'EOF'
          docker pull ${{ secrets.DOCKER_USERNAME }}/my-fe:latest
          docker pull ${{ secrets.DOCKER_USERNAME }}/my-be:latest

          cd ~/app
          docker-compose down
          docker-compose up -d
        EOF
